config/routes.rb
Gulch2::Application.routes.draw do
  resources :usage_fetcher
  resources :password_resets
  resources :sessions,      only: [:new, :create, :destroy]
  resources :sites
  resources :site_load_profiles
  resources :tarifftools
  resources :users
  
  root 'static_pages#home'
  match '/company', to: 'static_pages#company', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get' 
  match '/signout', to: 'sessions#destroy',     via: 'get'
  match '/input',   to: 'tariff_tools#input',   via: 'get'
  match '/tool',    to: 'tariff_tools#tool',    via: 'get'

  match '/input/save', to: 'tariff_tools#create', via: 'post'
  post '/site_load_profiles/:id'=> 'site_load_profiles#delete'
  match '/site/:id', to: 'sites#select', via: 'post'
  match 'tool/', to: 'tariff_tools#change_site_load_profile',  via: 'post'

  

end

app/models/site_load_profile.rb
class SiteLoadProfile < ActiveRecord::Base
	belongs_to :site

	validates :meter_read_date, presence: true	
	#validates :tou, presence: false	
	validates :data_source, presence: true	
	
	validates :all_usage, presence: true, numericality: true
	validates :all_demand, presence: true, numericality: true
	#validates :on_peak_usage, presence: false, numericality: true
	#validates :on_peak_demand, presence: false, numericality: true
	#validates :part_peak_usage, presence: false, numericality: true
	#validates :part_peak_demand, presence: false, numericality: true
	#validates :off_peak_usage, presence: false, numericality: true
	#validates :off_peak_demand, presence: false, numericality: true
	
	validates :site_id, presence: true


	def self.new_or_update(site_id, meter_read_date)
		@load_profile_check = SiteLoadProfile.where('site_id = ? 
							AND meter_read_date = ?', 
							site_id, meter_read_date)

		@data_status = Hash.new

		if @load_profile_check.count == 0
			@data_status = { :status => 'new', :id => nil }
		elsif @load_profile_check.count == 1
			#@new_or_update = { :status => 'update', :id => @load_profile_check.id }
			@data_status = { :status => 'update', :id => @load_profile_check.first.id }

		else
			# this is a big problem; 
			# => support needs to be aware and database needs to be fixed
			@data_status = { :status => 'error', :id => '999'}
		end

	end

	def self.find_all_load_profiles(site_id)
		@all_site_load_profiles = SiteLoadProfile.where('site_id = ?', site_id)

		@all_site_load_profiles.sort_by{ |a| a.meter_read_date }

	end

	def self.check_next(site_id, selected_site_load_profile_id)
		@list_site_load_profiles = SiteLoadProfile.find_all_load_profiles(site_id)

		if selected_site_load_profile_id != @list_site_load_profiles.last.id
			true
		else
			false
		end

	end

	def self.check_previous(site_id, selected_site_load_profile_id)
		@list_site_load_profiles = SiteLoadProfile.find_all_load_profiles(site_id)

		if selected_site_load_profile_id != @list_site_load_profiles.first.id
			true
		else
			false
		end
	end

	def self.get_next(site_id, selected_site_load_profile_id)
		@list_site_load_profiles = SiteLoadProfile.find_all_load_profiles(site_id)

		@current_index = @list_site_load_profiles.index{ |item| item.id == selected_site_load_profile_id }

		@previous_site_load_profile_id = @list_site_load_profiles[@current_index + 1].id
	end

	def self.get_previous(site_id, selected_site_load_profile_id)
		@list_site_load_profiles = SiteLoadProfile.find_all_load_profiles(site_id)

		@current_index = @list_site_load_profiles.index{ |item| item.id == selected_site_load_profile_id }

		@previous_site_load_profile_id = @list_site_load_profiles[@current_index - 1].id

	end

end

app/controllers/site_load_profiles_controller.rb
class SiteLoadProfilesController < ApplicationController
	before_action :signed_in_user

	def create
		@site = Site.find(params[:site_load_profile][:site_id])
		@site_load_profile = SiteLoadProfile.new(site_load_profile_params)

		# checks to see if a site_load_profile already matches on meter_read_date 
		@new_or_update = SiteLoadProfile.new_or_update(@site_load_profile.site_id, 
			@site_load_profile.meter_read_date)

		if @new_or_update[:status] == 'new'

			if @site_load_profile.save
				flash[:notice] = 'New Load Profile data added.'
				redirect_to site_load_profile_path(@site)
			else
				render 'show'
			end

		elsif @new_or_update[:status] == 'update'
			@site_load_profile = SiteLoadProfile.find(@new_or_update[:id])

  			if @site_load_profile.update(site_load_profile_params)
				flash[:notice] = 'Load Profile data updated.'
				redirect_to site_load_profile_path(@site)
			else
				render 'show'
			end

		elsif @new_or_update[:status] == 'error'
			flash[:notice] = 'An error has occured.  Our support team has 
				been made aware and will be fixing the problem shortly.'
			redirect_to site_load_profile_path(@site)
		end

	end

	def delete
		@site = Site.find(params[:site_id])
		@site_load_profile = SiteLoadProfile.find(params[:id])

		if @site_load_profile.destroy
			flash[:notice] = 'Site Load Profile data deleted.'
			redirect_to site_load_profile_path(@site)
		else
			flash[:notice] = 'An error has occured in an attempt to delete the Site Load Profile data.
							Support has been made aware and shall be in touch to address this issue.'
			# add email alert to support
			
		end

	end

	def edit
	end

	def new
		@site_load_profile = SiteLoadProfile.new
	end

	def select_site
		#for storing selected_site information
		@site = Site.find(params[:site_id])
		session[:selected_site_id] = @site.id
		#flash[:notice] = session[:selected_site_id]
		redirect_to site_load_profile_path(@site)

	end

	def show
		@site = Site.find(params[:id])
		@site_load_profile = SiteLoadProfile.new
	end

	private

		def site_load_profile_params
			params.require(:site_load_profile).permit(:meter_read_date, :data_source,
						:all_usage, :on_peak_usage, :part_peak_usage, :off_peak_usage,
						:all_demand, :on_peak_demand, :part_peak_demand, :off_peak_demand,  
						:site_id)
		end

end


app/views/site_load_profiles/_site_load_profile.html.erb
<tr>
  <td><%= site_load_profile.meter_read_date %></td>
  <!-- <td><%#= site_load_profile.data_source %></td> -->
  <td><%= site_load_profile.all_usage %></td>
  <td><%= site_load_profile.on_peak_usage %></td>
  <td><%= site_load_profile.part_peak_usage %></td>
  <td><%= site_load_profile.off_peak_usage %></td>
  <td><%= site_load_profile.all_demand %></td>
  <td><%= site_load_profile.on_peak_demand %></td>
  <td><%= site_load_profile.part_peak_demand %></td>
  <td><%= site_load_profile.off_peak_demand %></td>
  <!--<td><%#= link_to "Edit", 	edit_user_path(@user) %></td>-->
	<!--<td><%#= link_to "Select", 	edit_user_path(@user) %></td>-->
	<td><%= button_to "Delete", method: "delete", id: site_load_profile.id, 
                              site_id: site_load_profile.site_id %></td>
</tr>

app/views/site_load_profiles/new.html.erb
<title>Add to Load Profile</title>
<h1>Add to Load Profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@site_load_profile) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
		
      	<div>
      		<%= f.hidden_field :site_id, value: 266 %>
      	</div>

  	   	<div class="left">
  	      	<%= f.label :meter_read_date %>
  	      	<%= f.date_field :meter_read_date %>
  	  	</div>

    		<div class="right">
      		<%= f.label :tou, "Time of User" %>
      		<%= f.select :tou, ['All', 'Peak', 'Part-Peak', 'Off-Peak'] %>
      	</div>

  	  	<div class="left">
        		<%= f.label :demand, "Demand (in kW)" %>
        		<%= f.text_field :demand %>
    		</div>

       	<div class="right">
        		<%= f.label :usage, "Usage (in kWh)" %>
        		<%= f.text_field :usage %>
    		</div>
     			
      <%= f.submit "Save", class: "btn btn-med btn-custom" %>
    <% end %>

  </div>
</div>

<h1>Site Load Profile: </h1>
<%# if @site.site_load_profiles.any? %>
  <table>
    <tr>
      <td>Meter Read Date:</td>
      <td>Total Usage (kWh):</td>
      <td>On-Peak Usage (kWh):</td>
      <td>Part-Peak Usage (kWh):</td>
      <td>Off-Peak Usage (kWh):</td>
      <td>Billing Demand (kW):</td>
      <td>On-Peak Demand (kW):</td>
      <td>Part-Peak Demand (kW):</td>
      <td>Off-Peak Demand (kW):</td>
    </tr>
    <ol class="site_load_profiles">
      <%#= render @site_load_profiles %>
    </ol>
      <%#= will_paginate @sites %>
  </table>
<%# else %>
  <p> No load profile saved </p>
<%# end %>

app/views/site_load_profiles/show.html.erb

<title>Site Details and Load Profile</title>

<p id="notice"><%= notice %></p>

<h1>Site Details:</h1>

<table>
      <tr>
            <td> Site Name: </td>
            <td><%= @site.site_name %></td>

            <td></td>
            <td></td>

            <td> Address: </td>
            <td><%= @site.address %></td>
      </tr>
      <tr>
            <td> Company: </td>
            <td><%= @site.company %></td>

            <td></td>
            <td></td>

            <td> City: </td>
            <td><%= @site.city %></td>
      </tr>
      <tr>
            <td> Industry Type: </td>
            <td><%= @site.industry_type %></td>

            <td></td>
            <td></td>

            <td> State: </td>
            <td><%= @site.state %></td>
      </tr>
      <tr>
            <td> Building Type: </td>
            <td><%= @site.building_type %></td>

            <td></td>
            <td></td>

            <td> Zip: </td>
            <td><%= @site.zip_code %></td>
      </tr>
      <tr>
            <td> Phases: </td>
            <td><%= @site.phases %></td>

            <td></td>
            <td></td>

            <td> Square Feet: </td>
            <td><%= @site.square_feet %></td>
      </tr>
      <tr>
            <td> Description: </td>
            <td><%= @site.description %></td>
      </tr>

      <tr>
            <td> Is Site currently selected? </td>
            <td>
                  <% if @site.id == session[:selected_site_id] %>
                        <td>Yes</td>
                  <% else %>
                        <td></td>
                  <% end %>
            </td>

            <td>
                  <%#= button_to "Select", action: "select_site", site_id: @site.id %>
            </td>

      </tr>
</table>

<%= link_to "Edit Site Info", edit_site_path(@site) %>      


<h1>Site Load Profile: </h1>


<% if @site.site_load_profiles.any? %>
      <table>
            <tr>
                  <td>Meter Read Date:</td>
                  <!-- <td>Data Source:</td> -->
                  <td>All Usage (kWh):</td>
                  <td>On-Peak Usage (kWh):</td>
                  <td>Part-Peak Usage (kWh):</td>
                  <td>Off-Peak Usage (kWh):</td>
                  <td>All Demand (kW):</td>
                  <td>On-Peak Demand (kW):</td>
                  <td>Part-Peak Demand (kW):</td>
                  <td>Off-Peak Demand (kW):</td>
            </tr>
            
            <ol class="sites">
                  <%= render @site.site_load_profiles %>
            </ol>
            
      </table>
<% else %>
<p> No load profile saved </p>
<% end %>


<h1>Change Site Load Profile:</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@site_load_profile, url: { action: "create" }) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
            
            <div>
                  <%= f.hidden_field :site_id, value: @site.id %>
                  <%= f.hidden_field :data_source, value: 'Monthly' %>
            </div>

            <div class="center">
                  <%= f.label :meter_read_date %>
                  <%= f.date_field :meter_read_date %>
            </div>

            <div class="left">
                  <%= f.label :all_usage, "All Usage (in kWh)" %>
                  <%= f.text_field :all_usage %>
            </div>

            <div class="right">
                  <%= f.label :all_demand, "All Demand (in kW)" %>
                  <%= f.text_field :all_demand %>
            </div>

            <div class="left">
                  <%= f.label :on_peak_usage, "On-Peak Usage (in kWh)" %>
                  <%= f.text_field :on_peak_usage %>
            </div>

            <div class="right">
                  <%= f.label :on_peak_demand, "On-Peak Demand (in kW)" %>
                  <%= f.text_field :on_peak_demand %>
            </div>

            <div class="left">
                  <%= f.label :part_peak_usage, "Part-Peak Usage (in kWh)" %>
                  <%= f.text_field :part_peak_usage %>
            </div>

            <div class="right">
                  <%= f.label :part_peak_demand, "Part-Peak Demand (in kW)" %>
                  <%= f.text_field :part_peak_demand %>
            </div>

            <div class="left">
                  <%= f.label :off_peak_usage, "Off-Peak Usage (in kWh)" %>
                  <%= f.text_field :off_peak_usage %>
            </div>

            <div class="right">
                  <%= f.label :off_peak_demand, "Off-Peak Demand (in kW)" %>
                  <%= f.text_field :off_peak_demand %>
            </div>
                  
      <%= f.submit "Change Load Profile", class: "btn btn-med btn-custom" %>
    <% end %>

  </div>
</div>