config/routes.rb
Gulch2::Application.routes.draw do
  resources :usage_fetcher
  resources :password_resets
  resources :sessions,      only: [:new, :create, :destroy]
  resources :sites
  resources :site_load_profiles
  resources :tarifftools
  resources :users
  
  root 'static_pages#home'
  match '/company', to: 'static_pages#company', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get' 
  match '/signout', to: 'sessions#destroy',     via: 'get'
  match '/input',   to: 'tariff_tools#input',   via: 'get'
  match '/tool',    to: 'tariff_tools#tool',    via: 'get'

  match '/input/save', to: 'tariff_tools#create', via: 'post'
  post '/site_load_profiles/:id'=> 'site_load_profiles#delete'
  match '/site/:id', to: 'sites#select', via: 'post'
  match 'tool/', to: 'tariff_tools#change_site_load_profile',  via: 'post'

  

end

app/models/site.rb
class Site < ActiveRecord::Base
	belongs_to :user
	has_many :site_load_profiles, dependent: :destroy

	#VALID_ZIP_REGEX = /\d{5}/ 								#zip_code
	validates :zip_code, numericality: true, 
				length: {minimum: 5, maximum: 5}
	#validates :square_feet, numericality: true
	validates :user_id, presence: true 			

	# should only be present when site is being saved	
	# validates :site_name, presence: true

	accepts_nested_attributes_for :site_load_profiles

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
	before_action :signed_in_user

	def new
		@site = Site.new
	end

	def create
		@site = Site.new(site_params)

		if @site.save
			flash[:notice] = 'New Site has been created.'
			redirect_to site_load_profile_path(@site)
		else
			render 'new'
		end
	end

	def destroy
	end


	def edit
		@site = Site.find(params[:id])
	end


	def select
		#for storing selected_site information
		@site = Site.find(params[:site_id])
		session[:selected_site_id] = @site.id
		session[:selected_site_load_profile_id] = nil
		#flash[:notice] = session[:selected_site_load_profile_id]
		redirect_to site_path(current_user)

	end

	def show
		#@site = Site.find(params[:id])
		#@user = User.find(params[:id])
	end

	def update
		@site = Site.find(params[:id])

		if @site.update_attributes(site_params)
			flash[:notice] = 'Site info has been updated.'
			redirect_to site_load_profile_path(@site)
		else
			render 'edit'
		end
	end

	private

	  	def site_params
	  		params.require(:site).permit(:site_name, :company, 
	  						:industry_type, :building_type, :description, 
	  						:address, :city, :state, :zip_code, :square_feet, 
	  						:phases, :user_id, :is_site_saved)
	  	end

end

app/views/sites/_site.html.erb
<% if site.is_site_saved == true %>

	<tr>
	  	<% if site.id == session[:selected_site_id] %>
	  		<td>Yes</td>
	  	<% else %>
	  		<td></td>
	  	<% end %>
	  	
	  	<td><%= site.site_name %></td>
	  	<td><%= site.company %></td>
	  	<td><%= site.city %></td>
	  	<td><%= site.state %></td>
	  	<td><%= site.description %></td>
	  	<td><%= link_to "View", site_load_profile_path(site) %></td>
	  	<!--<td><%#= link_to "Edit", edit_user_path(@user) %></td>-->

		<td><%= button_to "Select", action: "select", site_id: site.id %></td>

		<!--<td><%#= link_to "Delete", edit_user_path(@user) %></td>-->
		
	</tr>

<% end %>

app/views/sites/edit.html.erb
<title>Edit Site Info</title>
<h1>Edit Site Info</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@site) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
		
      	<div>
      		<%= f.hidden_field :user_id, value: @current_user.id %>
      	</div>

		<div class="left">
	      	<%= f.label :site_name %>
	      	<%= f.text_field :site_name %>
	  	</div>

		<div class="right">
    		<%= f.label :address %>
    		<%= f.text_field :address %>
    	</div>

	  	<div class="left">
      		<%= f.label :company %>
      		<%= f.text_field :company %>
  		</div>

      	<div class="right">
      		<%= f.label :city %>
      		<%= f.text_field :city %>
  		</div>

  		<div class="left">
      		<%= f.label :industry_type %>
      		<%= f.select :industry_type, ['Commercial'] %>
	  		<!--<%#= f.select :industry_type, ['Commercial', 'Manufacturing'] %>-->      
      	</div>

		<div class="right">
      		<%= f.label :state %>
      		<%= f.text_field :state %>
      	</div>

      	<div class="left">
      		<%= f.label :building_type %>
      		<%= f.select :building_type, ['Education', 'Food Sales', 'Food Service', 'Health Care (Inpatient)', 'Health Care (Outpatient)', 'Lodging', 'Mercantile (Retail Other Than Mall)', 'Mercantile (Enclosed and Strip Malls)', 'Office', 'Public Assembly', 'Public Order and Safety', 'Religious Worship', 'Service', 'Warehouse and Storage', 'Other', 'Vacant' ] %>
      	</div>
		
		<div class="right">
      		<%= f.label :zip_code %>
      		<%= f.text_field :zip_code %>
    	</div>

      	<br>
      	<br>

		<div class="center">
      		<%= f.label :description %>
      		<%= f.text_field :description %>
      	</div>

    	<br>

      	<div class="left">
      		<%= f.label :phases %>
      		<%= f.select :phases, ['3-phase','1-phase'] %>
      	</div>

    	<div class="right">
      		<%= f.label :square_feet %>
      		<%= f.text_field :square_feet %>
     	</div>

     	<br> <!-- enters a blank line, ie: line break -->
     	<br>
     			
      <%= f.submit "Update Site Info", class: "btn btn-med btn-custom" %>
    <% end %>

  </div>
</div>

app/views/sites/new.html.erb
<title>Create A New Site</title>
<h1>Create A New Site</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@site) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
		
      	<div>
      		<%= f.hidden_field :user_id, value: @current_user.id %>
          <%= f.hidden_field :is_site_saved, value: true %>
      	</div>

		<div class="left">
	      	<%= f.label :site_name %>
	      	<%= f.text_field :site_name %>
	  	</div>

		<div class="right">
    		<%= f.label :address %>
    		<%= f.text_field :address %>
    	</div>

	  	<div class="left">
      		<%= f.label :company %>
      		<%= f.text_field :company %>
  		</div>

      	<div class="right">
      		<%= f.label :city %>
      		<%= f.text_field :city %>
  		</div>

  		<div class="left">
      		<%= f.label :industry_type %>
      		<%= f.select :industry_type, ['Commercial'] %>
	  		<!--<%#= f.select :industry_type, ['Commercial', 'Manufacturing'] %>-->      
      	</div>

		<div class="right">
      		<%= f.label :state %>
      		<%= f.text_field :state %>
      	</div>

      	<div class="left">
      		<%= f.label :building_type %>
      		<%= f.select :building_type, ['Education', 'Food Sales', 'Food Service', 'Health Care (Inpatient)', 'Health Care (Outpatient)', 'Lodging', 'Mercantile (Retail Other Than Mall)', 'Mercantile (Enclosed and Strip Malls)', 'Office', 'Public Assembly', 'Public Order and Safety', 'Religious Worship', 'Service', 'Warehouse and Storage', 'Other', 'Vacant' ] %>
      	</div>
		
		<div class="right">
      		<%= f.label :zip_code %>
      		<%= f.text_field :zip_code %>
    	</div>

      	<br>
      	<br>

		<div class="center">
      		<%= f.label :description %>
      		<%= f.text_field :description %>
      	</div>

    	<br>

      	<div class="left">
      		<%= f.label :phases %>
      		<%= f.select :phases, ['3-phase','1-phase'] %>
      	</div>

    	<div class="right">
      		<%= f.label :square_feet %>
      		<%= f.text_field :square_feet %>
     	</div>

     	<br> <!-- enters a blank line, ie: line break -->
     	<br>
     			
      <%= f.submit "Create New Site", class: "btn btn-med btn-custom" %>
    <% end %>

  </div>
</div>

app/views/sites/show.html.erb

<h1>Sites: </h1>

<p id="notice"><%= notice %></p>

<% if current_user.sites.count(:is_site_saved) > 0 %>
      <table>
            <tr>
                  <td>Site Selected?</td>
                  <td>Site Name:</td>
                  <td>Company:</td>
                  <td>City:</td>
                  <td>State:</td>
                  <td>Description:</td>
            </tr>
            <ol class="sites">
                  <%= render current_user.sites %>
            </ol>
            <%#= will_paginate @sites %>
      </table>
<% else %>
<p> No sites saved </p>
<% end %>

<%= link_to "Create New Site", new_site_path %>
