config/routes.rb
Gulch2::Application.routes.draw do
  resources :usage_fetcher
  resources :password_resets
  resources :sessions,      only: [:new, :create, :destroy]
  resources :sites
  resources :site_load_profiles
  resources :tarifftools
  resources :users
  
  root 'static_pages#home'
  match '/company', to: 'static_pages#company', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get' 
  match '/signout', to: 'sessions#destroy',     via: 'get'
  match '/input',   to: 'tariff_tools#input',   via: 'get'
  match '/tool',    to: 'tariff_tools#tool',    via: 'get'

  match '/input/save', to: 'tariff_tools#create', via: 'post'
  post '/site_load_profiles/:id'=> 'site_load_profiles#delete'
  match '/site/:id', to: 'sites#select', via: 'post'
  match 'tool/', to: 'tariff_tools#change_site_load_profile',  via: 'post'

  

end

app/views/layouts/_footer.html.erb
<footer id="footer">
  <small>
    <ul> 
      <li> 650 W. Lake - Chicago, IL </li>
      <li>  (630) 248-0777  </li>
      <li> <a href="mailto:info@gulchsolutions.com"class="link"> info@gulchsolutions.com</a></li> 
    </ul>
   
  </small>
 <!--  <nav>
    <ul>
 
    </ul>
  </nav> -->

  <br>
  <br>

<!-- Google Tracking Code -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45478712-1', 'gulchsolutions.com');
  ga('send', 'pageview');

</script>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Gulch Solutions", root_path, id: "logo" %>
      <ul class="nav pull-right">
      	  <% if signed_in? %>
            <li><%= link_to "Profile",          current_user %></li>
            <li><%= link_to "Sites",            site_path(current_user) %></li>
            <li><%= link_to "Bill Comparison",  tool_path %></li>
            <li><%= link_to "Get Usage",        new_usage_fetcher_path %></li>
            <li><%= link_to "Sign Out",         signout_path %></li>            
          <% else %>
            <li><%= link_to "View Demo",  signin_path %></li>
            <li><%= link_to "Company",    company_path %></li>
            <li><%= link_to "Contact",    contact_path %></li>
            <li><%= link_to "Sign In",    signin_path %></li>
          <% end %>
          
        </ul>
      </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gulch Solutions</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
    <div class="container">
    	<% flash.each do |key, value| %>
    		<%= content_tag(:div, value, class: "alert alert-#{key}") %>
    	<% end %>
    	<%= yield %>
    	<%= debug(params) if Rails.env.development? %>
             <%= render 'layouts/footer' %>
    </div>
</body>

</html>